version: '3'
services:
  dvwa:
    image: vulnerables/web-dvwa
    ports:
    - "8080:80"
    volumes:
    - ./cors_vulnerability.php:/var/www/html/cors_vulnerability.php
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=dvwa
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    depends_on:
    - db
  db:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=dvwa
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password